# -*- coding: utf-8 -*-
"""BERT.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14SX0H9OxnhRh_nCBQdalJboW8h3kRll_
"""

from google.colab import drive
drive.mount('/content/drive')

!pip install fasttext

import pandas as pd
import numpy as np
import tensorflow as tf
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import classification_report, confusion_matrix
import matplotlib.pyplot as plt
import seaborn as sns
from transformers import AutoTokenizer, TFBertModel
import fasttext

# 1. Load Dataset
file_path = '/content/drive/My Drive/categorized_data_normalized.xlsx'
data = pd.read_excel(file_path)
texts = data['cleaned_content_normalized'].tolist()
labels = data['category']

# 2. Label Encoding
label_encoder = LabelEncoder()
encoded_labels = label_encoder.fit_transform(labels)

# 3. Train-Test Split
X_train, X_test, y_train, y_test = train_test_split(
    texts, encoded_labels, test_size=0.2, random_state=42
)

# 4. Load Pretrained BERT Model and Tokenizer
model_name = 'bert-base-uncased'
tokenizer = AutoTokenizer.from_pretrained(model_name)

# Tokenisasi BERT
def bert_tokenize_and_encode(texts):
    return tokenizer(texts, truncation=True, padding="max_length", max_length=128, return_tensors="tf")

train_encodings = bert_tokenize_and_encode(X_train)
test_encodings = bert_tokenize_and_encode(X_test)

# 5. Load Pretrained FastText Model
fasttext_model_path = '/content/drive/My Drive/wiki.id.bin'  # Path model FastText
ft = fasttext.load_model(fasttext_model_path)

# Generate FastText Embedding
def get_fasttext_embedding(texts, ft_model):
    embeddings = []
    for text in texts:
        words = text.split()
        word_vectors = [ft_model.get_word_vector(word) for word in words]
        if word_vectors:
            embeddings.append(np.mean(word_vectors, axis=0))  # Mean pooling
        else:
            embeddings.append(np.zeros(ft_model.get_dimension()))  # Vektor nol untuk teks kosong
    return np.array(embeddings)

train_fasttext = get_fasttext_embedding(X_train, ft)
test_fasttext = get_fasttext_embedding(X_test, ft)

# 6. Custom Model dengan BERT + FastText tanpa Freeze Layer
bert_model = TFBertModel.from_pretrained(model_name)

# Ensure that all layers are trainable (no freezing)
for layer in bert_model.layers:
    layer.trainable = True

# Input untuk BERT
input_ids = tf.keras.layers.Input(shape=(128,), dtype=tf.int32, name="input_ids")
attention_mask = tf.keras.layers.Input(shape=(128,), dtype=tf.int32, name="attention_mask")
bert_output = bert_model(input_ids, attention_mask=attention_mask).pooler_output

# Input untuk FastText
fasttext_input = tf.keras.layers.Input(shape=(300,), dtype=tf.float32, name="fasttext_embedding")

# Gabungkan BERT dan FastText embeddings
concatenated = tf.keras.layers.Concatenate()([bert_output, fasttext_input])

# Dense layers
dense1 = tf.keras.layers.Dense(256, activation="relu")(concatenated)
dropout = tf.keras.layers.Dropout(0.5)(dense1)
output = tf.keras.layers.Dense(len(label_encoder.classes_), activation="softmax")(dropout)

# Model
model = tf.keras.Model(inputs=[input_ids, attention_mask, fasttext_input], outputs=output)

# 7. Compile Model
model.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=2e-5),
    loss=tf.keras.losses.SparseCategoricalCrossentropy(),
    metrics=["accuracy"]
)

# 8. Latih Model
history = model.fit(
    [train_encodings["input_ids"], train_encodings["attention_mask"], train_fasttext],
    y_train,
    validation_data=(
        [test_encodings["input_ids"], test_encodings["attention_mask"], test_fasttext],
        y_test
    ),
    epochs=3,
    batch_size=32
)

# 9. Evaluasi Model
y_pred_probs = model.predict([test_encodings["input_ids"], test_encodings["attention_mask"], test_fasttext])
y_pred = np.argmax(y_pred_probs, axis=1)

# Print classification report
print(classification_report(y_test, y_pred, target_names=label_encoder.classes_))

# 10. Confusion Matrix
cm = confusion_matrix(y_test, y_pred)

# Plot confusion matrix
plt.figure(figsize=(10, 7))
sns.heatmap(cm, annot=True, fmt='d', cmap="Blues", xticklabels=label_encoder.classes_, yticklabels=label_encoder.classes_)
plt.title('Confusion Matrix')
plt.xlabel('Predicted Labels')
plt.ylabel('True Labels')
plt.show()

# 11. Visualisasi Model Performance
plt.figure(figsize=(12, 4))
plt.subplot(1, 2, 1)
plt.plot(history.history['accuracy'], label='Training Accuracy')
plt.plot(history.history['val_accuracy'], label='Validation Accuracy')
plt.title('Training and Validation Accuracy')
plt.xlabel('Epochs')
plt.ylabel('Accuracy')
plt.legend()

plt.subplot(1, 2, 2)
plt.plot(history.history['loss'], label='Training Loss')
plt.plot(history.history['val_loss'], label='Validation Loss')
plt.title('Training and Validation Loss')
plt.xlabel('Epochs')
plt.ylabel('Loss')
plt.legend()

plt.show()